spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://39.108.102.215:3307/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: redis
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 39.108.102.215:8848
        namespace: 9369b24b-60ef-4d86-abac-8b7f148b9bbb
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 9012
rocketmq:
  name-server: 42.194.149.227:9876
  producer:
    group: my-group
